# Generated by Django 5.2.1 on 2025-05-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPayTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('session_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('buy_order', models.CharField(max_length=100)),
                ('authorization_code', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_type_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
