# Generated by Django 5.2.1 on 2025-05-17 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_carrito'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carrito',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='productos.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='agregado_en',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='producto',
        ),
    ]
